SKY_BLUE = 'SkyBlue1'
LIGHT_BLUE = 'light slate blue'
LIGHT_GREEN = 'lightgreen'
LIGHT_SALMON = 'light salmon'
FONT_TIMES = 'Times'
MIN_TEXT_ROW = 20
MIN_TEXT_COL = 5
TYPE_AHEAD = 'TYPE_AHEAD'
BREAK = 'break'
WORD_SEP = ' '
CURSOR_SEP = '.'
ERROR = 'ERROR'
INFO = 'INFO'
TEXTAREA_START = '1.0'  # in tkinter, the text actually starts from row 1, col 0
TEXTAREA_END = 'end-1c'  # tkinter inserts a new line after the text. we dont need to remove it.
NEW_LINE_CHAR = '\n'
ALL_INPUT_KEYS = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
LABELS_KEY = 'labels'
SHORTCUT_LABELS_KEY = 'label_shortcuts'
PARENT_TITLE = 'Span Annotator'
TAG_START_B = '/B-'
TAG_START_I = '/I-'
UNDO_KEY = '<Control-z>'
UNLABEL_CMD = 'unlabel'
UNLABEL_KEY = 'q'
RE_LABEL_KEY = '<Control-r>'
TYPE_AHEAD_LISTBOX_HEIGHT = 5
TYPE_AHEAD_LISTBOX_WIDTH = 25
TYPE_AHEAD_ENTRY_WIDTH = 25
TYPE_AHEAD_NO_RESULTS_MESSAGE = "No results found for '{0:}'"
RESERVED_SHORT_CUT_CHARS = ['q', 'r', 'z']
HIGHLIGHT_TAG_NAME = 'highlight'
